name: CI/CD pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push React app
      uses: docker/build-push-action@v2
      with:
        context: ./eco_connect/src/main/reactfront  # React 앱의 디렉토리
        push: true
        tags: gin1/reactfront:latest

    - name: Build and push Spring Boot app
      uses: docker/build-push-action@v2
      with:
        context: ./eco_connect  # Spring Boot 앱의 디렉토리
        push: true
        tags: gin1/spring-app:latest

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker pull gin1/reactfront:latest
          docker pull gin1/springboot:latest
          docker-compose up -d
